services:
  - type: web
    name: eagleinsight
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python train_model.py
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT